# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AskQuestion(self, question: str,approved_terms_json: str,schema_and_samples: str,retry_note: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AskResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AskQuestion(question=question,approved_terms_json=approved_terms_json,schema_and_samples=schema_and_samples,retry_note=retry_note,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AskQuestion", args={
                "question": question,"approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,"retry_note": retry_note,
            })
            return typing.cast(types.AskResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DraftActionTicket(self, insight_text: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionDraftResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DraftActionTicket(insight_text=insight_text,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DraftActionTicket", args={
                "insight_text": insight_text,
            })
            return typing.cast(types.ActionDraftResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DraftOntologyMetrics(self, schema_and_samples: str,inferred_joins_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DraftMetricsResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DraftOntologyMetrics(schema_and_samples=schema_and_samples,inferred_joins_json=inferred_joins_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DraftOntologyMetrics", args={
                "schema_and_samples": schema_and_samples,"inferred_joins_json": inferred_joins_json,
            })
            return typing.cast(types.DraftMetricsResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def InterpretQueryResult(self, question: str,sql: str,result_json: str,terms_used_json: str,
        baml_options: BamlCallOptions = {},
    ) -> types.InsightInterpretation:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.InterpretQueryResult(question=question,sql=sql,result_json=result_json,terms_used_json=terms_used_json,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="InterpretQueryResult", args={
                "question": question,"sql": sql,"result_json": result_json,"terms_used_json": terms_used_json,
            })
            return typing.cast(types.InsightInterpretation, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SuggestAskQuestions(self, approved_terms_json: str,schema_and_samples: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SuggestQuestionsResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SuggestAskQuestions(approved_terms_json=approved_terms_json,schema_and_samples=schema_and_samples,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SuggestAskQuestions", args={
                "approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,
            })
            return typing.cast(types.SuggestQuestionsResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AskQuestion(self, question: str,approved_terms_json: str,schema_and_samples: str,retry_note: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AskResponse, types.AskResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AskQuestion", args={
            "question": question,"approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,"retry_note": retry_note,
        })
        return baml_py.BamlStream[stream_types.AskResponse, types.AskResponse](
          __result__,
          lambda x: typing.cast(stream_types.AskResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AskResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DraftActionTicket(self, insight_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ActionDraftResponse, types.ActionDraftResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DraftActionTicket", args={
            "insight_text": insight_text,
        })
        return baml_py.BamlStream[stream_types.ActionDraftResponse, types.ActionDraftResponse](
          __result__,
          lambda x: typing.cast(stream_types.ActionDraftResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionDraftResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DraftOntologyMetrics(self, schema_and_samples: str,inferred_joins_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.DraftMetricsResponse, types.DraftMetricsResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DraftOntologyMetrics", args={
            "schema_and_samples": schema_and_samples,"inferred_joins_json": inferred_joins_json,
        })
        return baml_py.BamlStream[stream_types.DraftMetricsResponse, types.DraftMetricsResponse](
          __result__,
          lambda x: typing.cast(stream_types.DraftMetricsResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DraftMetricsResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def InterpretQueryResult(self, question: str,sql: str,result_json: str,terms_used_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.InsightInterpretation, types.InsightInterpretation]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="InterpretQueryResult", args={
            "question": question,"sql": sql,"result_json": result_json,"terms_used_json": terms_used_json,
        })
        return baml_py.BamlStream[stream_types.InsightInterpretation, types.InsightInterpretation](
          __result__,
          lambda x: typing.cast(stream_types.InsightInterpretation, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.InsightInterpretation, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SuggestAskQuestions(self, approved_terms_json: str,schema_and_samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SuggestQuestionsResponse, types.SuggestQuestionsResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SuggestAskQuestions", args={
            "approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,
        })
        return baml_py.BamlStream[stream_types.SuggestQuestionsResponse, types.SuggestQuestionsResponse](
          __result__,
          lambda x: typing.cast(stream_types.SuggestQuestionsResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SuggestQuestionsResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AskQuestion(self, question: str,approved_terms_json: str,schema_and_samples: str,retry_note: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AskQuestion", args={
            "question": question,"approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,"retry_note": retry_note,
        }, mode="request")
        return __result__
    async def DraftActionTicket(self, insight_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftActionTicket", args={
            "insight_text": insight_text,
        }, mode="request")
        return __result__
    async def DraftOntologyMetrics(self, schema_and_samples: str,inferred_joins_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftOntologyMetrics", args={
            "schema_and_samples": schema_and_samples,"inferred_joins_json": inferred_joins_json,
        }, mode="request")
        return __result__
    async def InterpretQueryResult(self, question: str,sql: str,result_json: str,terms_used_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InterpretQueryResult", args={
            "question": question,"sql": sql,"result_json": result_json,"terms_used_json": terms_used_json,
        }, mode="request")
        return __result__
    async def SuggestAskQuestions(self, approved_terms_json: str,schema_and_samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SuggestAskQuestions", args={
            "approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AskQuestion(self, question: str,approved_terms_json: str,schema_and_samples: str,retry_note: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AskQuestion", args={
            "question": question,"approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,"retry_note": retry_note,
        }, mode="stream")
        return __result__
    async def DraftActionTicket(self, insight_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftActionTicket", args={
            "insight_text": insight_text,
        }, mode="stream")
        return __result__
    async def DraftOntologyMetrics(self, schema_and_samples: str,inferred_joins_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DraftOntologyMetrics", args={
            "schema_and_samples": schema_and_samples,"inferred_joins_json": inferred_joins_json,
        }, mode="stream")
        return __result__
    async def InterpretQueryResult(self, question: str,sql: str,result_json: str,terms_used_json: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="InterpretQueryResult", args={
            "question": question,"sql": sql,"result_json": result_json,"terms_used_json": terms_used_json,
        }, mode="stream")
        return __result__
    async def SuggestAskQuestions(self, approved_terms_json: str,schema_and_samples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SuggestAskQuestions", args={
            "approved_terms_json": approved_terms_json,"schema_and_samples": schema_and_samples,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))