# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AskQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AskResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AskQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.AskResponse, __result__)

    def DraftActionTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionDraftResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DraftActionTicket", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionDraftResponse, __result__)

    def DraftOntologyMetrics(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DraftMetricsResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DraftOntologyMetrics", llm_response=llm_response, mode="request")
        return typing.cast(types.DraftMetricsResponse, __result__)

    def InterpretQueryResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InsightInterpretation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InterpretQueryResult", llm_response=llm_response, mode="request")
        return typing.cast(types.InsightInterpretation, __result__)

    def SuggestAskQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SuggestQuestionsResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SuggestAskQuestions", llm_response=llm_response, mode="request")
        return typing.cast(types.SuggestQuestionsResponse, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AskQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AskResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AskQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AskResponse, __result__)

    def DraftActionTicket(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionDraftResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DraftActionTicket", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionDraftResponse, __result__)

    def DraftOntologyMetrics(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DraftMetricsResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DraftOntologyMetrics", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DraftMetricsResponse, __result__)

    def InterpretQueryResult(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InsightInterpretation:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="InterpretQueryResult", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InsightInterpretation, __result__)

    def SuggestAskQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SuggestQuestionsResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SuggestAskQuestions", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SuggestQuestionsResponse, __result__)

    