# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class ActionDraftResponse(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='short imperative title')
    body: typing.Optional[str] = Field(default=None, description='what happened, the evidence numbers, and \'Suggested owner: BI Analyst on-call\'')

class AskResponse(BaseModel):
    sql: typing.Optional[str] = Field(default=None, description='SELECT ... a single read-only SELECT (or WITH...SELECT), DuckDB dialect, referencing only real tables/columns')
    terms_used: typing.List[str] = Field(description='ids of the ontology terms you relied on')
    reasoning_one_line: typing.Optional[str] = None

class DraftMetric(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='snake_case id prefixed with m_, e.g. m_active_customer')
    name: typing.Optional[str] = Field(default=None, description='Human Name')
    definition: typing.Optional[str] = Field(default=None, description='one sentence')
    sql: typing.Optional[str] = Field(default=None, description='SELECT ... valid DuckDB SQL referencing REAL columns only; must be a single SELECT')
    source_tables: typing.List[str] = Field(description='table names this metric is computed from')
    confidence: typing.Optional[float] = Field(default=None, description='0..1')

class DraftMetricsResponse(BaseModel):
    metrics: typing.List["DraftMetric"] = Field(description='3-5 useful business metrics')

class InsightInterpretation(BaseModel):
    has_insight: typing.Optional[bool] = None
    text: typing.Optional[str] = Field(default=None, description='direct one-to-two sentence answer to the user\'s question, grounded in the query result — always filled in, regardless of has_insight')
    severity: typing.Optional[str] = Field(default=None, description='\'info\' for a routine answer; \'warning\' or \'critical\' only when has_insight is true and the pattern is concerning')
    warrants_action: typing.Optional[bool] = None
    reasoning_one_line: typing.Optional[str] = None

class SuggestQuestionsResponse(BaseModel):
    questions: typing.List[str] = Field(description='3-5 short, concrete questions a business user could ask about THIS data — reference real object/metric names, not generic BI cliches')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
