# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ActionDraftResponse": types.ActionDraftResponse,
    "stream_types.ActionDraftResponse": stream_types.ActionDraftResponse,

    "types.AskResponse": types.AskResponse,
    "stream_types.AskResponse": stream_types.AskResponse,

    "types.DraftMetric": types.DraftMetric,
    "stream_types.DraftMetric": stream_types.DraftMetric,

    "types.DraftMetricsResponse": types.DraftMetricsResponse,
    "stream_types.DraftMetricsResponse": stream_types.DraftMetricsResponse,

    "types.InsightInterpretation": types.InsightInterpretation,
    "stream_types.InsightInterpretation": stream_types.InsightInterpretation,


}