# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (5)
# #########################################################################

class ActionDraftResponse(BaseModel):
    title: str = Field(description='short imperative title')
    body: str = Field(description='what happened, the evidence numbers, and \'Suggested owner: BI Analyst on-call\'')

class AskResponse(BaseModel):
    sql: str = Field(description='SELECT ... a single read-only SELECT (or WITH...SELECT), DuckDB dialect, referencing only real tables/columns')
    terms_used: typing.List[str] = Field(description='ids of the ontology terms you relied on')
    reasoning_one_line: str

class DraftMetric(BaseModel):
    id: str = Field(description='snake_case id prefixed with m_, e.g. m_active_customer')
    name: str = Field(description='Human Name')
    definition: str = Field(description='one sentence')
    sql: str = Field(description='SELECT ... valid DuckDB SQL referencing REAL columns only; must be a single SELECT')
    source_tables: typing.List[str] = Field(description='table names this metric is computed from')
    confidence: float = Field(description='0..1')

class DraftMetricsResponse(BaseModel):
    metrics: typing.List["DraftMetric"] = Field(description='3-5 useful business metrics')

class InsightInterpretation(BaseModel):
    has_insight: bool
    text: str = Field(description='one-sentence insight description; empty if has_insight is false')
    severity: str = Field(description='\'info\', \'warning\', or \'critical\'; empty if has_insight is false')
    warrants_action: bool
    reasoning_one_line: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
